apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keiser-garmin-sync-data
  labels:
    app: keiser-garmin-sync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: your-storage-class
